//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NhaHangNVDEntities : DbContext
    {
        public NhaHangNVDEntities()
            : base("name=NhaHangNVDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Album> Album { get; set; }
        public virtual DbSet<BanAn> BanAn { get; set; }
        public virtual DbSet<CongThucMonAn> CongThucMonAn { get; set; }
        public virtual DbSet<ChiNhanh> ChiNhanh { get; set; }
        public virtual DbSet<DatCho> DatCho { get; set; }
        public virtual DbSet<HoaDon> HoaDon { get; set; }
        public virtual DbSet<KhachHang> KhachHang { get; set; }
        public virtual DbSet<KhuyenMai> KhuyenMai { get; set; }
        public virtual DbSet<MonAn> MonAn { get; set; }
        public virtual DbSet<NCC> NCC { get; set; }
        public virtual DbSet<NDHoaDon> NDHoaDon { get; set; }
        public virtual DbSet<NhanVien> NhanVien { get; set; }
        public virtual DbSet<NhanVienRole> NhanVienRole { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<SuKien> SuKien { get; set; }
        public virtual DbSet<ThucDon> ThucDon { get; set; }
        public virtual DbSet<VatTu> VatTu { get; set; }
        public virtual DbSet<VnPayResult> VnPayResult { get; set; }
    }
}
