//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibData
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhuyenMai
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string NoiDung { get; set; }
        public Nullable<int> KMPhanTram { get; set; }
        public Nullable<int> KMTienMat { get; set; }
        public int TinhTrang { get; set; }
        public System.DateTime NgayTao { get; set; }
        public Nullable<System.DateTime> NgaySua { get; set; }
    }
}
