//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibData
{
    using System;
    using System.Collections.Generic;
    
    public partial class NDHoaDon
    {
        public int Id { get; set; }
        public int IdHoaDon { get; set; }
        public int IdMonAn { get; set; }
        public long Giatien { get; set; }
        public int SoLuong { get; set; }
        public int ThanhTien { get; set; }
        public System.DateTime NgayTao { get; set; }
        public Nullable<System.DateTime> NgaySua { get; set; }
    
        public virtual HoaDon HoaDon { get; set; }
        public virtual MonAn MonAn { get; set; }
    }
}
